### ISSUE TITLE
Empty pages and weird 'n' symbols in output

### ISSUE THREAD

**Issue by russkel** [tobiasBora/Scribd-downloader#1]
Hi Tobias,
Thanks for your script. I seem to be having some issues with downloading this PDF:
https://www.scribd.com/doc/236735923/3-Gelfand-Glagoleva-Kirilov-The-Method-of-coordinates-pdf

The resulting PDF is this:
https://drive.google.com/file/d/0B954aoLBYNShMm1pVnVKaFNfYWM/view?usp=sharing

Any ideas?

Regards,

Russ

**Comment by tobiasBora** [comment]
Hello,

I saw that Scribd changed its page structure so I have to modify my 
code. I have some works, but I'll try to work on it soon. If I forget it 
please recall me.

Sorry,

Tobias.

**Comment by d3zorg** [comment]
is there any news?

**Comment by tobiasBora** [comment]
Hello,

Scribd seems to be able to detect that I'm a script and don't provide my 
the page. I'm playing with differents tools (wkhtmltopdf, phantomjs...) 
and there is always a problem. I'm trying to find a workaround but I 
don't know when I'll find one... If anyone manage to get a screenshot of 
the content of the page I would be happy to hear about it.

Sorry for the inconvenience, I hope I'll find a solution soon.

Tobias Bora.

**Comment by kenorb** [comment]
The same problem for this [link](http://www.scribd.com/doc/217826903/Understanding-John-Searl-s-SEG).

**Comment by tobiasBora** [comment]
I have a good news, I found a solution to my main problem ! Now I need to code it and it may be long, but I'm happy to see that the main problem is solved ! I will tell you when the solution is usable.

**Comment by ryanjdillon** [comment]
I have just tried the script and received a blank document of correct page length.

**Comment by tobiasBora** [comment]
Hello!

I've some news. I won't support anymore this repository, but I created a new one here: https://github.com/tobiasBora/scribd-downloader-3 . On this project, your page works great.

**Comment by tobiasBora** [comment]
Hum, in fact it works better, but there are some troubles in the page size, I'll try to fix it.

**Comment by tobiasBora** [comment]
Ok problem fixed in the new repo, it was buggy because all the pages had a different size. Should work now!

**Comment by russkel** [comment]
Oh awesome. I had forgotten about this issue. Thanks tobias, will give the new repo a shot.
