### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by birone** [tobiasBora/Scribd-downloader#2]
Sadly, as I was really looking forward to using it :) :

$ scribd_download.sh http://fr.scribd.com/doc/63942746/chopin-nocturne-n-20-partition
Getting informations...
(It can be quite long, and don't worry if
you see some errors during the conversion)
  Number of pages... 0
  Title... 
Done.
## Removing useless parts...

Done
Downloading page...
The first detection didn't work...
Width :  px
Height :  px
~/bin/scribd_download.sh: line 266: \* 2: syntax error: operand expected (error token is "\* 2")
~/bin/scribd_download.sh: line 267: \* 2: syntax error: operand expected (error token is "\* 2")
All pages have been downloaded, I will now create the pdf file
Using pdftk (maybe longer but no memory error)
You can change the configuration if you prefer convert
convert.im6: unable to open image `0_*.png': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file`0__.png' @ error/png.c/ReadPNGImage/3667.
convert.im6: no images defined `0__.png.pdf' @ error/convert.c/ConvertImageCommand/3044.

Checked dependencies:
~$ apt-cache show pdftk
Package: pdftk
...
Version: 2.01-1
~$ apt-cache show phantomjs
Package: phantomjs
...
Version: 1.9.0-1
~$ apt-cache show imagemagick
Package: imagemagick
...
Version: 8:6.7.7.10-6ubuntu3

(I just copied scribd_download.sh to my ~/bin and did chmod 755. Please let me know if there are things I should try...)

**Comment by tobiasBora** [comment]
Hello,

Since a few weeks I have some trouble to make my script work, I wonder if Scribd doesn't detect my script… I'm going to try to go through this problem but I cannot give any garanty it will work.

Sorry for the inconvenience,

Tobias.

On 5 mars 2015 21:36:35 HNEC, birone notifications@github.com wrote:

> Sadly, as I was really looking forward to using it :) :
> 
> $ scribd_download.sh
> http://fr.scribd.com/doc/63942746/chopin-nocturne-n-20-partition
> Getting informations...
> (It can be quite long, and don't worry if
> you see some errors during the conversion)
>  Number of pages... 0
>  Title... 
> Done.
> 
> ## Removing useless parts...
> 
> Done
> Downloading page...
> The first detection didn't work...
> Width :  px
> Height :  px
> ~/bin/scribd_download.sh: line 266: \* 2: syntax error: operand expected
> (error token is "\* 2")
> ~/bin/scribd_download.sh: line 267: \* 2: syntax error: operand expected
> (error token is "\* 2")
> All pages have been downloaded, I will now create the pdf file
> Using pdftk (maybe longer but no memory error)
> You can change the configuration if you prefer convert
> convert.im6: unable to open image `0_*.png': No such file or directory
> @ error/blob.c/OpenBlob/2638.
> convert.im6: unable to open file`0__.png' @
> error/png.c/ReadPNGImage/3667.
> convert.im6: no images defined `0__.png.pdf' @
> error/convert.c/ConvertImageCommand/3044.
> 
> Checked dependencies:
> ~$ apt-cache show pdftk
> Package: pdftk
> ...
> Version: 2.01-1
> ~$ apt-cache show phantomjs
> Package: phantomjs
> ...
> Version: 1.9.0-1
> ~$ apt-cache show imagemagick
> Package: imagemagick
> ...
> Version: 8:6.7.7.10-6ubuntu3
> 
> (I just copied scribd_download.sh to my ~/bin and did chmod 755. Please
> let me know if there are things I should try...)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tobiasBora/Scribd-downloader/issues/2

## 

Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by birone** [comment]
Ok - thanks for letting me know, and good luck!

**Comment by tobiasBora** [comment]
Hello!
I just wanted to let you know that this repo is not supported anymore, but I created a new one here: https://github.com/tobiasBora/scribd-downloader-3 . This one seems to work pretty nicely for what I tried now.
