### ISSUE TITLE
Bad download

### ISSUE THREAD

**Issue by neupuceni** [tobiasBora/Scribd-downloader#3]
From terminal view, script works fine. But, when you look the pdf its just, saved webpage without css and images. And, "window" for document isn't shown.

**Comment by tobiasBora** [comment]
Hello,

I know, Scribd seems to detect my script and I can't manage to make it work anymore. I'm going to tsy to solve this bug when I have more free time but I cannot give any warranty it will work.

Sory for the inconvenience,

TobiasBora.

On 31 mars 2015 13:27:29 HAEC, neupuceni notifications@github.com wrote:

> From terminal view, script works fine. But, when you look the pdf its
> just, saved webpage without css and images. And, "window" for document
> isn't shown. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tobiasBora/Scribd-downloader/issues/3

## 

Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by tobiasBora** [comment]
I won't support anymore this repository, but I created a new one here: https://github.com/tobiasBora/scribd-downloader-3 . This projects seems to work pretty nicely, but if you find some documents that are not supported please report them.
