### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by redbarrol** [tobiasBora/Scribd-downloader#8]
When I do this :  ./scribd_download.sh 'https://www.scribd.com/doc/133354180/00002-Ejercicios-Resueltos-Geometria-Plana' , I get error, I could be fixed?

 ./scribd_download.sh 'https://www.scribd.com/doc/133354180/00002-Ejercicios-Resueltos-Geometria-Plana'
Getting informations...
(It can be quite long, and don't worry if
you see some errors during the conversion)
  Number of pages... 07
  Title... 00002_Ejercicios_Resueltos_Geometria_Plana
Done.
Removing useless parts...
---------------
Done
Downloading page...
Detection successfull !
Width : 902 px
Height : 1276 px
Downloading 7 pages (0 leaving pages after that, 0 already downloaded)
Done
Treatment... 
convert-im6.q16: Image height exceeds user limit in IHDR `out.png' @ warning/png.c/MagickPNGWarningHandler/1654.
convert-im6.q16: Invalid IHDR data `out.png' @ error/png.c/MagickPNGErrorHandler/1628.
convert-im6.q16: corrupt image `out.png' @ error/png.c/ReadPNGImage/3963.
convert-im6.q16: no images defined `0_00000.png' @ error/convert.c/ConvertImageCommand/3258.

**Comment by tobiasBora** [comment]
I won't support anymore this repository, but I created a new one here: https://github.com/tobiasBora/scribd-downloader-3 . On this project, your page works great.
