### ISSUE TITLE
PDF was completely blank

### ISSUE THREAD

**Issue by Rich700000000000** [tobiasBora/Scribd-downloader#9]
I just tried it, and the resulting PDF had 100 pages that were completely blank. How can I fix this?

**Comment by karstengit** [comment]
Me the same. It would be wonderful if this script would work.
I tried both options with the same result:
pdf_convert_mode="pdftk"
pdf_convert_mode="convert"

**Comment by karstengit** [comment]
I could find out that the pages are downloaded correctly in .tmp.
There is the right content in page.html and page_svg.html and both files are identical.
But then something is going wrong with the conversion to png.
It must be phantom_render.js in .tmp that it not working!

I don't know why the pages are converted to png to get an pdf?

**Comment by tobiasBora** [comment]
Hello,

Sorry for the time I took to answer, but I'm really busy these days. Unfortunately, I don't have time to maintain this script, and I know it's buggy. Last time, I spent 2 hours to create a new version from scratch. It was working fine for my small 10 pages example, but for bigger example I think I should add a sleeper that wait the page to be fully loaded. However, it's possible that this script works for you, can you test it? You can find it here: https://github.com/tobiasBora/scribd-downloader-3

If it's not working, please fill an issue on this repo, and give the url to a buggy file. I may take some time for you to see why it's not working.

**Comment by karstengit** [comment]
Thank you for your answer Tobias.
It is really nice that you offered your scribd solution, so i can't await support.
I will try your new script.
This "old" solution is using javascript - why you are leaving it?

**Comment by tobiasBora** [comment]
Ok, so I did some update on the new repo, now it can deal with big documents and hidden ones.

I'm leaving this old solution for several reasons:
1) bash is nice on linux, but not supported on Windows, so it can't be a cross platform tool.
2) I got some problems with PhantomJs with some Nvidia cards
3) Debugging PhantomJs is more complicated that debugging Selenium (I can try live modifications with Seleniumà
4) Selenium let me run javascript code directly, and I don't need anymore to do dirty hacks to modify/read the html page like `page_name=`cat page.html | egrep -o "<title>.*</title>" | sed -E 's/<title>(.*)<\/title>/\1/' | sed -e 's/ /_/g' | tr -cd '[[:alnum:]]._-'``, I can directly ask in javascript what I want. And it's *really* a big confort.

**Comment by karstengit** [comment]
Thanks for the comments.
Some wicked remarks from me to your points: :-)
1. Windows user want to pay for the software, so they don't need your tool.
2. I didn't understand how you grab the information. Now i have an idea. https://en.wikipedia.org/wiki/PhantomJS
3. I never used PhantomJS or Selenium. But this is an good idea from you!
4. O.K. I will believe this.

Then all will happen in the next version at https://github.com/tobiasBora/scribd-downloader-3
